language: minimal

# stages:

matrix:
  include:
  - os: linux
    dist: bionic
    addons:
      snaps:
      - name: powershell
        confinement: classic
        channel: latest/stable
  - os: linux
    dist: bionic
    addons:
      snaps:
      - name: powershell-preview
        confinement: classic
        channel: latest/stable
    before_install:
      - sudo snap alias pwsh pwsh-preview
  - os: osx
    before_install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew cask install powershell
  - os: osx
    before_install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew tap Homebrew/cask-versions && HOMEBREW_NO_AUTO_UPDATE=1 brew cask install powershell-preview && ln -s /usr/local/bin/pwsh-preview /usr/local/bin/pwsh

# install:
#   - pwsh -f '${env:TRAVIS_BUILD_DIR}/install-dependencies.ps1'

# before_script:
#   - pwsh -f '${env:TRAVIS_BUILD_DIR}/build.ps1'

script:
# - pwsh -File "${TRAVIS_BUILD_DIR}/pake.ps1" 'test'
- pwsh -File "${TRAVIS_BUILD_DIR}/fail.ps1"

# after_success:
#   - pwsh -f '${env:TRAVIS_BUILD_DIR}/deploy.ps1'
