language: minimal

# stages:

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        snaps:
          - name: powershell
            confinement: classic
            channel: latest/stable
      script:
        - pwsh -File "${TRAVIS_BUILD_DIR}/pake.ps1" 'test'
    - os: linux
      dist: bionic
      addons:
        snaps:
          - name: powershell-preview
            confinement: classic
            channel: latest/stable
      script:
        - pwsh-preview -File "${TRAVIS_BUILD_DIR}/pake.ps1" 'test'
    - os: osx
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew cask install powershell
      script:
        - pwsh -File "${TRAVIS_BUILD_DIR}/pake.ps1" 'test'
    - os: osx
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew tap Homebrew/cask-versions && HOMEBREW_NO_AUTO_UPDATE=1 brew cask install powershell-preview
      script:
        - pwsh-preview -File "${TRAVIS_BUILD_DIR}/pake.ps1" 'test'

# install:
#   - pwsh -f '${env:TRAVIS_BUILD_DIR}/install-dependencies.ps1'

# before_script:
#   - pwsh -f '${env:TRAVIS_BUILD_DIR}/build.ps1'

# script:
#   - pwsh-preview -version; pwsh -version
  # - pwsh -File "${TRAVIS_BUILD_DIR}/pake.ps1" 'test'

# after_success:
#   - pwsh -f '${env:TRAVIS_BUILD_DIR}/deploy.ps1'
