language: minimal

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell-preview
      before_install:
        - sudo ln -s /usr/bin/pwsh-preview /usr/bin/pwsh
    - os: osx
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew config && HOMEBREW_NO_AUTO_UPDATE=1 brew cask install powershell
    - os: osx
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew config && HOMEBREW_NO_AUTO_UPDATE=1 brew tap Homebrew/cask-versions && HOMEBREW_NO_AUTO_UPDATE=1 brew cask install powershell-preview && ln -s /usr/local/bin/pwsh-preview /usr/local/bin/pwsh

install:
  - pwsh -NonInteractive -File "${TRAVIS_BUILD_DIR}/pake.ps1" dep

script:
  - pwsh -NonInteractive -File "${TRAVIS_BUILD_DIR}/pake.ps1" unit
